# Generated by Django 4.2.28 on 2026-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='max_capacity',
            field=models.IntegerField(default=50, help_text='Maximum orders per break slot'),
        ),
    ]
